### ISSUE TITLE
关于修改数据集后出现的一些问题

### ISSUE THREAD

**Issue by GeniusLittleFlyingPig** [lab-sun/MAFNet#3]
您好，首先非常感谢您能分享代码供大家进行学习，我在对数据集进行了一些修改后再进行训练，训练结果就会出现如下问题，请问这是为什么呢？
Epoch pothole glob acc : 90.8884, pre_p : nan, recall_p : 0.0000, F_score_p : nan, IoU_p : 0.0000
Epoch background glob acc : 90.8884, pre_b : 90.8884, recall_b : 100.0000, F_score_b : 95.2267, IoU_b : 90.8884
Average pre :nan, recall: 50.0000, F_score: nan, IoU : 45.4442

**Comment by Dr-zfeng** [comment]
您好，可以介绍一下对数据集进行了什么修改么？
在训练过程中，Transformer的部分不容易从零开始训练。建议先load我们提供的weight，然后在这个基础上进行训练

**Comment by GeniusLittleFlyingPig** [comment]
您好，非常感谢您及时的回答。我是对train文件夹下的部分图片进行了部分替换，再对其进行了数据加强，文件命名和您提供的数据集有所不同，不过txt文件也进行了同步的更改，之后再进行训练很多时候就会出现上述所提到的问题。我在训练中有使用您提供的预训练权重。在今天中午的时候，成功训练了一次，但是效果下降较多，这可能是什么原因导致的呢
同时还想再请问一下label文件夹中全黑的图片是用来做什么的呀，以及您所提供的数据增强应该怎么使用呢，麻烦了。

**Comment by GeniusLittleFlyingPig** [comment]
而且发现训练结果对大范围坑洞的检测效果比较差，不过预训练权重结果看起来挺好的，这个是怎么解决的呢

**Comment by Dr-zfeng** [comment]
> 您好，非常感谢您及时的回答。我是对train文件夹下的部分图片进行了部分替换，再对其进行了数据加强，文件命名和您提供的数据集有所不同，不过txt文件也进行了同步的更改，之后再进行训练很多时候就会出现上述所提到的问题。我在训练中有使用您提供的预训练权重。在今天中午的时候，成功训练了一次，但是效果下降较多，这可能是什么原因导致的呢 同时还想再请问一下label文件夹中全黑的图片是用来做什么的呀，以及您所提供的数据增强应该怎么使用呢，麻烦了。

1. 你训练了多少个epoch呢？训练的效果和训练的epoch数量有关系，同时和train的图片数量+图片的尺寸都有关系。
2. 黑色的图片是label，就是标注的坑洞的像素。因为只分割坑洞一个类别，因此每张图像的像素值只有0（未标注）和1（坑洞），因此看起来是黑色的。如果想对其可视化，可以将每个像素乘以255就可以了看到了。
3. 我们提供的图像数据是增强过的图像，如果有需求，你可以直接在这我们提供的图像上进行再处理

**Comment by Dr-zfeng** [comment]
> 而且发现训练结果对大范围坑洞的检测效果比较差，不过预训练权重结果看起来挺好的，这个是怎么解决的呢

建议调小训练的初始学习率

**Comment by GeniusLittleFlyingPig** [comment]
好的好的，谢谢您。我是训练了100个epoch，因为感觉后续再训练得到的评估值差不多。我再研究研究，再次感谢您！

**Comment by GeniusLittleFlyingPig** [comment]
不好意思又来打扰您，我想直接使用label_visual作为真值，不过运行起来会报如下错误：
RuntimeError: stack expects each tensor to be equal size, but got [512, 512] at entry 0 and [512, 512, 3] at entry 1
请问这需要修改什么地方呢？

**Comment by Dr-zfeng** [comment]
> 不好意思又来打扰您，我想直接使用label_visual作为真值，不过运行起来会报如下错误： RuntimeError: stack expects each tensor to be equal size, but got [512, 512] at entry 0 and [512, 512, 3] at entry 1 请问这需要修改什么地方呢？

label_visual 是三通道的，读入之后要变成单通道的，然后将单通道进行归一化就ok了

**Comment by GeniusLittleFlyingPig** [comment]
没找到怎么改，方便指导一下嘛T T

**Comment by GeniusLittleFlyingPig** [comment]
我对训练集中label下的图片直接进行一些翻转操作进行扩充，发现还是会出现上述报错ＴＴ
